name: Run Locust Tests on Commit

on:
  push:
    branches:
      - main

jobs:
  locust-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Start Flask server
      run: |
        python3 server.py &
        echo "Waiting for Flask server to start"
        sleep 30

    - name: Run Locust tests
      run: |
        locust --headless -u 10000 -r 100 -t 3m -H http://127.0.0.1:5000 > locust_results.txt

    - name: Upload Locust results
      uses: actions/upload-artifact@v3
      with:
        name: locust-results
        path: locust_results.txt
